# 開発ステージのベースイメージを指定
FROM node:16-alpine

# 作業ディレクトリを作成
WORKDIR /app

# 依存関係のインストールに必要なファイルを先にコピー
COPY package.json package-lock.json ./

# 依存関係をインストール (このステップはキャッシュされる)
RUN npm install

# 残りのソースコードをコピー (頻繁に変更される部分)
COPY . .

# 開発サーバーのポートを公開
EXPOSE 3000

# React開発サーバーを起動
CMD ["npm", "start"]



# 以下正常起動確認
# # ビルドステージのベースイメージを指定
# FROM node:16-alpine AS build-stage

# # 作業ディレクトリを作成
# WORKDIR /app

# # package.json と package-lock.json をコピー
# COPY package.json package-lock.json ./

# # 依存関係をインストール
# RUN npm install

# # ソースコードをコピー
# COPY . .

# # Reactアプリをビルド
# RUN npm run build

# # 最終ステージでNginxを使って静的ファイルを提供
# FROM nginx:alpine
# COPY --from=build-stage /app/build /usr/share/nginx/html

# # コンテナが公開するポート番号
# EXPOSE 80

# # Nginxの起動
# CMD ["nginx", "-g", "daemon off;"]
