# 本番用

# ビルドステージ
FROM node:16-alpine AS build-stage
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Nginxステージ
FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

# Nginxでアプリを提供
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
