# 本番用

# ビルドステージでNode.jsを使用してReactアプリをビルド
FROM node:16-alpine AS build-stage

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Nginxを使って静的ファイルを提供
FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
